from io import StringIO
from pathlib import Path

from pytest import raises, warns

from py2puml.asserts import assert_py2puml_command_args, assert_py2puml_ios

from tests import PROJECT_PATH

ACTUAL_CONTENTS = """@startuml contact
!pragma useIntermediatePackages false

class Contact {
  name: str
}
footer Generated by //py2puml//
@enduml
"""

EXPECTED_CONTENTS = """@startuml contact
!pragma useIntermediatePackages false

class Contact {
  fullname: str
}
footer Generated by //py2puml//
@enduml
"""


def test_assert_py2puml_ios_with_unmatching_ios():
    with raises(ValueError) as error:
        assert_py2puml_ios(StringIO(ACTUAL_CONTENTS), StringIO(EXPECTED_CONTENTS), 'py2puml -p contact')

    assert (
        str(error.value) == "Line 5 is '  name: str' but '  fullname: str' was expected (source: 'py2puml -p contact')"
    )


def test_assert_py2puml_command_args_with_invalid_args():
    with raises(ValueError) as error:
        assert_py2puml_command_args('py2puml -p contact', Path.cwd() / 'contact.puml')

    assert (
        str(error.value)
        == "The command should contain only the arguments without reference to the py2puml executable, got 'py2puml -p contact'"
    )


def test_assert_py2puml_command_args_with_runtime_error():
    with raises(RuntimeError) as error:
        assert_py2puml_command_args(
            '-p tests/modules/withrootnotincwd -n modules.withrootnotincwd', Path.cwd() / 'withrootnotincwd.puml'
        )

    assert (
        str(error.value)
        == "An error occurred when running 'py2puml -p tests/modules/withrootnotincwd -n modules.withrootnotincwd'"
    )


def test_assert_py2puml_command_args_warns_on_overwrite_mode_in_stdout():
    with warns(
        UserWarning, match=r"assert_py2puml_command_args\(\) is used to overwrite file '.+py2puml\.domain\.puml'"
    ):
        assert_py2puml_command_args(
            '-p py2puml/domain', PROJECT_PATH / 'py2puml' / 'py2puml.domain.puml', overwrite_expected_output=True
        )


def test_assert_py2puml_command_args_warns_on_overwrite_mode_in_file(tmp_path):
    with warns(
        UserWarning, match=r"assert_py2puml_command_args\(\) is used to overwrite file '.+py2puml\.domain\.puml'"
    ):
        assert_py2puml_command_args(
            f'-p py2puml/domain -o {tmp_path / "py2puml.domain.puml"}',
            PROJECT_PATH / 'py2puml' / 'py2puml.domain.puml',
            overwrite_expected_output=True,
        )
