name: Python package

on: [push]

env:
  MIN_CODE_COVERAGE_PERCENT: 92

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'poetry'
      - name: Install project dependencies
        run: poetry install --without lint
      - name: Run automated tests (with code coverage)
        run: poetry run pytest -v --cov=py2puml --cov-branch --cov-report term-missing --cov-fail-under $MIN_CODE_COVERAGE_PERCENT
